Cl/build improvements (#535)
* Barretenberg tests run in parallel on spot instances.

* wip

diff --git a/.circleci/build b/.circleci/build
--- a/.circleci/build
+++ b/.circleci/build
@@ -15,26 +15,40 @@ set -e
 
 REPOSITORY=$1
 BRANCH=${CIRCLE_BRANCH//\//_}
-MASTER_TAG=master-$LAST_SUCCESSFUL_COMMIT
-IMAGE_MASTER_URI=$ECR_URL/$REPOSITORY:$MASTER_TAG
 IMAGE_BRANCH_URI=$ECR_URL/$REPOSITORY:cache-$BRANCH
 IMAGE_COMMIT_URI=$ECR_URL/$REPOSITORY:cache-$CIRCLE_SHA1
 DOCKERFILE=${2:-./Dockerfile}
 
-# Ensure ECR repository exists.
-ensure_repo $REPOSITORY $ECR_REGION
-
-# Check if we should rebuild.
-check_rebuild || ! image_exists $REPOSITORY $MASTER_TAG || { echo "No rebuild necessary." && exit 0; }
-
 function fetch_image() {
   echo "Pulling: $1"
-  if ! docker pull $1 > /dev/null 2>&1; then
+  # TODO: revert. debugging random pull failures from dockerhub.
+  #if ! docker pull $1 > /dev/null 2>&1; then
+  if ! docker pull $1; then
     echo "Image not found: $1"
     return 1
   fi
   return 0
 }
+
+# Login to dockerhub.
+echo "$DOCKERHUB_PASSWORD" | docker login -u aztecprotocolci --password-stdin
+
+# Ensure ECR repository exists.
+ensure_repo $REPOSITORY $ECR_REGION refresh_lifecycle
+
+LAST_SUCCESSFUL_COMMIT=$(last_successful_commit $REPOSITORY)
+echo "Last successful commit: $LAST_SUCCESSFUL_COMMIT"
+
+# If we have previously successful commit, we can early out if nothing relevant has changed since.
+if ! check_rebuild $LAST_SUCCESSFUL_COMMIT; then
+  echo "No rebuild necessary. Retagging..."
+  STAGES=$(cat $DOCKERFILE | sed -n -e 's/^FROM .* AS \(.*\)/\1/p')
+  for STAGE in $STAGES; do
+    tag_remote_image $REPOSITORY cache-$LAST_SUCCESSFUL_COMMIT-$STAGE cache-$CIRCLE_SHA1-$STAGE
+  done
+  tag_remote_image $REPOSITORY cache-$LAST_SUCCESSFUL_COMMIT cache-$CIRCLE_SHA1
+  exit 0
+fi
 
 # Pull latest parents that are not ours.
 PARENTS=$(cat $DOCKERFILE | sed -n -e 's/^FROM \([^[:space:]]\+\).*/\1/p' | grep -v $ECR_DEPLOY_URL | sort | uniq)
@@ -42,44 +56,58 @@ for PARENT in $PARENTS; do
   fetch_image $PARENT
 done
 
-# For each parent that's ours, pull in the newly rebuilt image if it's present.
-# If it's not present, there must be a master image to use.
+# For each parent that's ours, pull in the latest image.
 PARENTS=$(cat $DOCKERFILE | sed -n -e "s/^FROM $ECR_DEPLOY_URL\/\([^[:space:]]\+\)/\1/p")
 for PARENT in $PARENTS; do
+  # Extract repository name (i.e. discard tag).
   PARENT_REPO=${PARENT%:*}
-  PARENT_IMAGE_URI=$ECR_URL/$PARENT_REPO:cache-$CIRCLE_SHA1
-  if ! fetch_image $PARENT_IMAGE_URI; then
-    PARENT_IMAGE_URI=$ECR_URL/$PARENT_REPO:$MASTER_TAG
-    fetch_image $PARENT_IMAGE_URI
+  PARENT_COMMIT_HASH=$(last_successful_commit $PARENT_REPO)
+  # There must be a parent image to continue.
+  if [ -z "$PARENT_COMMIT_HASH" ]; then
+    echo "No parent image found for $PARENT_REPO"
+    exit 1
   fi
+  PARENT_IMAGE_URI=$ECR_URL/$PARENT_REPO:cache-$PARENT_COMMIT_HASH
+  echo "Pulling dependency $PARENT_REPO..."
+  fetch_image $PARENT_IMAGE_URI
+  # Tag it to look like an official release as that's what we use in Dockerfiles.
   docker tag $PARENT_IMAGE_URI $ECR_DEPLOY_URL/$PARENT
 done
-
-# Pull image from cache.
-echo "Pulling previous build of $REPOSITORY..."
-fetch_image $IMAGE_BRANCH_URI || fetch_image $IMAGE_MASTER_URI || true
-CACHE_FROM="--cache-from $IMAGE_BRANCH_URI --cache-from $IMAGE_MASTER_URI"
-echo
 
 # Pull, build and push each named stage to cache.
 STAGES=$(cat $DOCKERFILE | sed -n -e 's/^FROM .* AS \(.*\)/\1/p')
 for STAGE in $STAGES; do
-  echo "Pulling stage: $STAGE"
-  STAGE_IMAGE_MASTER_URI=$ECR_URL/$REPOSITORY:cache-master-$STAGE
-  STAGE_IMAGE_BRANCH_URI=$ECR_URL/$REPOSITORY:cache-$BRANCH-$STAGE
-
-  fetch_image $STAGE_IMAGE_BRANCH_URI || fetch_image $STAGE_IMAGE_MASTER_URI || true
-  STAGE_CACHE_FROM="--cache-from $STAGE_IMAGE_BRANCH_URI --cache-from $STAGE_IMAGE_MASTER_URI"
-  CACHE_FROM="$STAGE_CACHE_FROM $CACHE_FROM"
+  # Get the last build of this stage to leverage layer caching.
+  if [ -n "$LAST_SUCCESSFUL_COMMIT" ]; then
+    echo "Pulling stage: $STAGE"
+    STAGE_IMAGE_LAST_URI=$ECR_URL/$REPOSITORY:cache-$LAST_SUCCESSFUL_COMMIT-$STAGE
+    if fetch_image $STAGE_IMAGE_LAST_URI; then
+      STAGE_CACHE_FROM="--cache-from $STAGE_IMAGE_LAST_URI"
+    fi
+  fi
 
   echo "Building stage: $STAGE"
-  docker build --target $STAGE $STAGE_CACHE_FROM -t $STAGE_IMAGE_BRANCH_URI -f $DOCKERFILE .
+  STAGE_IMAGE_COMMIT_URI=$ECR_URL/$REPOSITORY:cache-$CIRCLE_SHA1-$STAGE
+  docker build --target $STAGE $STAGE_CACHE_FROM -t $STAGE_IMAGE_COMMIT_URI -f $DOCKERFILE .
+
+  # We don't want to have redo this stages work when building the final image. Use it as a layer cache.
+  CACHE_FROM="--cache-from $STAGE_IMAGE_COMMIT_URI $CACHE_FROM"
 
   echo "Pushing stage: $STAGE"
-  docker push $STAGE_IMAGE_BRANCH_URI > /dev/null 2>&1
+  docker push $STAGE_IMAGE_COMMIT_URI > /dev/null 2>&1
   echo
 done
 
+# Pull previous image to use it as a layer cache if it exists.
+if [ -n "$LAST_SUCCESSFUL_COMMIT" ]; then
+  LAST_SUCCESSFUL_URI=$ECR_URL/$REPOSITORY:cache-$LAST_SUCCESSFUL_COMMIT
+  echo "Pulling previous build of $REPOSITORY..."
+  fetch_image $LAST_SUCCESSFUL_URI || true
+  CACHE_FROM="--cache-from $LAST_SUCCESSFUL_URI $CACHE_FROM"
+  echo
+fi
+
+# Build the actual image and give it a branch and commit tag.
 echo "Building image: $IMAGE_BRANCH_URI, $IMAGE_COMMIT_URI"
 docker build -t $IMAGE_BRANCH_URI -t $IMAGE_COMMIT_URI -f $DOCKERFILE $CACHE_FROM .
 echo "Pushing image: $IMAGE_BRANCH_URI"
@@ -88,6 +116,7 @@ echo "Pushing image: $IMAGE_COMMIT_URI"
 docker push $IMAGE_COMMIT_URI > /dev/null 2>&1
 echo
 
+# Validate any terraform if it exists.
 if [ -d ./terraform ]; then
   ensure_terraform
   export TF_IN_AUTOMATION=1
