Fix.

diff --git a/.circleci/setup_env b/.circleci/setup_env
--- a/.circleci/setup_env
+++ b/.circleci/setup_env
@@ -4,10 +4,16 @@
 if [ "$CIRCLE_BRANCH" == "master" ]; then
   LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=100"
   LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '[.[] | select(.build_parameters.CIRCLE_JOB == "deploy")][0].vcs_revision'`
-  if [ "$LAST_SUCCESSFUL_COMMIT" == "null" ]; then
-    echo "Failed to find last successful commit. Perhaps it was too long ago? Find better solution."
-    exit 1
-  fi
+  OFFSET=0
+  while [ "$LAST_SUCCESSFUL_COMMIT" == "null" ]; do
+    OFFSET=$[OFFSET+100]
+    if [ "$OFFSET" -gt "1000" ]; then
+      echo "Failed to find last successful commit. Perhaps it was too long ago? Find better solution."
+      exit 1
+    fi
+    LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=100&offset=$OFFSET"
+    LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '[.[] | select(.build_parameters.CIRCLE_JOB == "deploy")][0].vcs_revision'`
+  done
   echo export LAST_SUCCESSFUL_COMMIT=$LAST_SUCCESSFUL_COMMIT >> $BASH_ENV
 else
   # CircleCI checkout mangles master for some reason. Reset it.
